steps:
- name: 'gcr.io/cloud-builders/gke-deploy'
  args: 
  - run
  - --filename=samples/bookinfo/platform/kube/bookinfo.yaml
  - --location=asia-northeast3-c
  - --cluster=sample-cluster
  - --namespace=istio
